version: '3.8'
volumes:
  postgres-data:

services:
  server:
    container_name: oauth_nest
    image: nestjs-oauth
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    command: yarn start:prod

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=oauth
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - RUN_AS_ROOT=true
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
